spring.application.name=webflux-alumnos
# Configuración de Liquibase
spring.liquibase.change-log=classpath:db.changelog-master.xml

# Configuración de la base de datos H2 para R2DBC (WebFlux)
spring.r2dbc.url=r2dbc:h2:mem:///alumnosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

# Configuración JDBC para Liquibase (necesario para migraciones)
spring.datasource.url=jdbc:h2:mem:alumnosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
