spring:
  application:
    name: webflux-alumnos

  # Conexion reactiva (R2DBC)
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool:
      enabled: true

  # Liquibase usando JDBC
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: false

logging:
  level:
    org.springframework.r2dbc: DEBUG
    rodriguez.ciro.webfluxalumnos: DEBUG
    liquibase: DEBUG

server:
  port: 8080
